### ISSUE TITLE
Extract security category mapping to tools

### ISSUE THREAD

**Issue by mrfyda** [codacy/codacy-meta#220]
We want to extract to the tools the responsibility of identifying security issues and their categories.

We are proposing to do that by adding a subcategory to the `patterns.json` API:
```
{
  "patternId": "S3330",
  "category": "Security",
  "subcategory": "XSS",
  "level": "Warning"
}
```
See discussion here: https://github.com/codacy/codacy-sonar-csharp/issues/19#issuecomment-537590360

Tools that need to be updated
- [x] Ameba (no security patterns)
- [x] Bandit https://github.com/codacy/codacy-bandit/pull/25
- [ ] BundlerAudit https://github.com/codacy/codacy-bundler-audit/pull/32
- [x] Checkstyle (Only style checks - as the name indicates)
- [x] Codacy ScalaMeta Pro
- [x] CoffeeLint (Only style checks)
- [x] cppcheck
- [x] credo https://github.com/codacy/codacy-credo/pull/22
- [x] CSSLint (no security checks)
- [x] Detekt (no security checks)
- [x] ESLint https://github.com/codacy/codacy-eslint/pull/11
- [x] Spotbugs https://github.com/codacy/codacy-meta/issues/294
- [x] Flawfinder https://github.com/codacy/codacy-flawfinder/pull/13
- [x] Hadolint https://github.com/codacy/codacy-hadolint/pull/11
- [x] JacksonLinter (no security checks)
- [x] JSHint (no security checks)
- [x] PHP CodeSniffer https://github.com/codacy/codacy-codesniffer/pull/40
- [ ] PHP MessDetector https://github.com/codacy/codacy-phpmd/issues/20
- [x] PMD https://github.com/codacy/codacy-pmdjava/pull/74
- [ ] Prospector
- [ ] PSScriptAnalyzer https://github.com/codacy/codacy-psscriptanalyzer/pull/17
- [ ] PyLint Legacy https://github.com/codacy/codacy-pylint/pull/58
- [ ] PyLint (Python 3) https://github.com/codacy/codacy-pylint-python3/pull/35
- [x] RemarkLint (no security checks)
- [ ] Rubocop https://github.com/codacy/codacy-rubocop/pull/62
- [x] ScalaMeta Pro https://github.com/codacy/codacy-meta/issues/280
- [ ] ScalaStyle (no security patterns)
- [ ] shellcheck https://github.com/codacy/codacy-shellcheck/pull/16
- [x] Sonar C# https://github.com/codacy/codacy-sonar-csharp/issues/19
- [x] ~~SQLint~~
- [x] ~~Stylelint~~
- [x] ~~SwiftLint~~
- [x] ~~tailor~~
- [x] ~~TSLint~~ https://github.com/sleekbyte/tailor/issues/424
- [ ] Codenarc https://github.com/codacy/codacy-codenarc/pull/8
- [x] Revive (no security patterns)
